import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navigation = [
  { title: "About", href: "/about" },
  { title: "Contact", href: "/contact" },
  { title: "Lectures", href: "/lectures" },
  { title: "Product", href: "/product" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          {/* <Link href="/about">About</Link> |{" "}
          <Link href="/contact">Contact</Link> */}
          {navigation.map((nav) => {
            return (
              <Link className=" mr-9" key={nav.title} href={nav.href}>
                {nav.title}
              </Link>
            );
          })}
        </div>
        <div>Header</div>
        {children}
      </body>
    </html>
  );
}
